### ISSUE TITLE
Betweenness Centrality

### ISSUE THREAD

**Issue by greghogan** [GraphIt-DSL/graphit#83]
From your paper six of the seven algorithms are included in the `apps` directory but Betweenness Centrality looks to be missing. Is this available for sharing? Thanks!

**Comment by yunmingzhang17** [comment]
Hi Greg, 

Yes, betweenness centrality is also available. We just haven't fully integrated into the test suite yet, and that's why it is not in the apps directory yet. 

You can find the algorithm file here 
https://github.com/GraphIt-DSL/graphit/blob/master/test/input/bc.gt

The corresponding schedules are here 
https://github.com/GraphIt-DSL/graphit/blob/master/test/input_with_schedules/bc_SparsePushDensePull_bitvector.gt

https://github.com/GraphIt-DSL/graphit/blob/master/test/input_with_schedules/bc_SparsePushDensePull.gt

https://github.com/GraphIt-DSL/graphit/blob/master/test/input_with_schedules/bc_SparsePush.gt

In general, we've got a few other applications, such as closeness centrality, under https://github.com/GraphIt-DSL/graphit/blob/master/test/input/ , and https://github.com/GraphIt-DSL/graphit/blob/master/test/input_with_schedules. 

Please let us know if you run into any issues running these applications. We are looking to integrate Betweenness Centrality into our correctness and performance test suite soon!

Best

Yunming

**Comment by yunmingzhang17** [comment]
bc.gt added to apps. Unit tests are also added in test_with_schedules.py.
